// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3HMbSSuWXDY7xt1YbwI90tUyxMo7jmjA',
    appId: '1:1075476022217:web:5d6f546e93f41f817b1e18',
    messagingSenderId: '1075476022217',
    projectId: 'namma-empire',
    authDomain: 'namma-empire.firebaseapp.com',
    storageBucket: 'namma-empire.firebasestorage.app',
    measurementId: 'G-WL5EM753L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3t5DEojmNX0Tz9qWZSyyuxZsKXrC20q0',
    appId: '1:1075476022217:android:97b8dbb9dd16ea747b1e18',
    messagingSenderId: '1075476022217',
    projectId: 'namma-empire',
    storageBucket: 'namma-empire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw0kG3E_MRKYUVu_MBK3VQCfWxh0GKTa4',
    appId: '1:1075476022217:ios:5b40cb5d6c9dc6187b1e18',
    messagingSenderId: '1075476022217',
    projectId: 'namma-empire',
    storageBucket: 'namma-empire.firebasestorage.app',
    iosClientId: '1075476022217-49orvcjecudcif8930vm3a4eh0fr8khj.apps.googleusercontent.com',
    iosBundleId: 'com.nammaempire.nammsign',
  );
}
